# -*- coding: utf-8 -*-
"""Load keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-dKuEjbWlNt4B7Ljn8kyFqrMbFkcN3F
"""

import urllib.request

print('Beginning file download with urllib2...')

url = 'https://www.kaggleusercontent.com/kf/26027417/eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..61P0rUNrwd6oWhmwhZSAzA.7TplxtNM3gbnB0dcK13WUJzrgONVHpSms_H8OXzkktsn9TPACdWedpuBMP9YpsiRNVO8sIIOvSkMnbc5lyHpXOpT9dkHXRH482gRWNvqjudHdRcGRAuCUXAJ4tpoB1fhPULv9u9061KSnJo1tkh4lW6IM2Aglix-EaCLw4wCexbGGK7I4xY9GKIadFZEK-rw.nTlYbGBWJMm6UPKrQn9aIw/model_num.h5'
urllib.request.urlretrieve(url, 'model_num.h5')

import numpy as np
import pickle
import cv2
from os import listdir
from sklearn.preprocessing import LabelBinarizer
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation, Flatten, Dropout, Dense
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam
from keras.preprocessing import image
from keras.preprocessing.image import img_to_array
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

EPOCHS = 25
INIT_LR = 1e-3
BS = 32
default_image_size = tuple((256, 256))
image_size = 0
directory_root = '../input/plantvillage/'
width=256
height=256
depth=3

import json

# read file
with open('/content/drive/My Drive/dataset/keras plant /model.json', 'r') as myfile:
    data=myfile.read()

# parse file
obj = json.loads(data)

from keras.models import model_from_json
model = model_from_json(data)

model.load_weights('/content/drive/My Drive/dataset/keras plant /model_num.h5')

model.summary()

# from keras.models import load_model
# model = load_model('/content/drive/My Drive/dataset/keras plant /model_num.h5')

model.summary()

def convert_image_to_array(image_dir):
    try:
        image = cv2.imread(image_dir)
        if image is not None :
            image = cv2.resize(image, default_image_size)   
            return img_to_array(image)
        else :
            return np.array([])
    except Exception as e:
        print(f"Error : {e}")
        return None

test_image =  convert_image_to_array('/content/ph.jpg')

# test_image.shape
resize_image = test_image.reshape((1,) + test_image.shape)

np.argmax(model.predict(resize_image))

list = ['Pepper__bell___Bacterial_spot', 'Pepper__bell___healthy',
 'Potato___Early_blight', 'Potato___Late_blight' ,'Potato___healthy',
 'Tomato_Bacterial_spot' ,'Tomato_Early_blight' ,'Tomato_Late_blight',
 'Tomato_Leaf_Mold', 'Tomato_Septoria_leaf_spot',
 'Tomato_Spider_mites_Two_spotted_spider_mite' ,'Tomato__Target_Spot',
 'Tomato__Tomato_YellowLeaf__Curl_Virus', 'Tomato__Tomato_mosaic_virus',
 'Tomato_healthy']

list[np.argmax(model.predict(resize_image))]

from google.colab import drive
drive.mount('/content/drive')

